# Generated by Django 5.0.2 on 2024-02-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Emp',
        ),
    ]
